name: sc-io-bench
id: sc_io_bench
description: This is a small benchmark just to understand I/O for single cell data in R and Python
benchmarker: "Mark Robinson <mark.robinson@mls.uzh.ch>"

# Benchmark configuration
version: "0.1.0"

# The default software environment for this benchmark.
# One of: apptainer, conda, envmodules.
software_backend: "apptainer"

# Available software environments
software_environments:
    r:
        name: r apptainer env
        description: A more verbose description, for humans reading this
        apptainer: envs/r.sif
#    py:
#        name: py env
#        description: A more verbose description, for humans reading this
#        conda: envs/py.yaml

# Stages and modules for your benchmark

stages:
  - id: datasets
    outputs:
        - id: data.out
          path: "{dataset}.out"
        - id: data.format
          path: "{dataset}.json"
    modules:
      - id: dataloader
        name: "loads the benchmark datasets"
        software_environment: "r"
        repository:
          url: https://github.com/markrobinsonuzh/sc-io-dataloader
          #url: https://github.com/markrobinsonuzh/sc-io-dataloader
          #url: /home/mark/projects/omb/sc-io-dataloader
          commit: main
        parameters:
            - dataset: "1.3m"
              subset: [1.0]
              format: ["h5ad"]
              #subset: [0.25, 0.50, 0.75, 1.0]
              #format: ["h5ad","mm","files"]

#  - id: reading
#    inputs:
#        - data.h5
#    outputs:
#      - id: reading.json
#        path: "{dataset}.json"
#    modules:
#      - id: sc-io-reader-r
#        name: "the only method you will ever need"
#        software_environment: "r"
#        repository:
#          url: https://github.com/markrobinsonuzh/sc-io-reader-r
#          commit: main
#        parameters:
#          - param1: "value"
#      - id: sc-io-reader-py
#        name: "the only method you will ever need"
#        software_environment: "py"
#        repository:
#          url: https://github.com/markrobinsonuzh/sc-io-reader-py
#          commit: main
#        parameters:
#          - seed: [1976, 2009, 2012]

